### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by Simek11** [stephenharris/WordPressBehatExtension#16]
I would like to use WordPress functions in my own FeatureContext class and write steps which are not presented in WordPressBehatExtension. Behat returns some issue when I try example from documentation. If my behat.yml file looks like this:

```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - \StephenHarris\WordPressBehatExtension\Context\WordPressContext
        - \StephenHarris\WordPressBehatExtension\Context\Plugins\WordPressPluginContext
  extensions:
    StephenHarris\WordPressBehatExtension:
      path: '/var/www/wordpress'
      connection:
        db: "wordpress"
        username: "wordpress"
        password: "wordpress"
      flush_database: false
      mail:
        directory: '/tmp/mail'
    Behat\MinkExtension:
      base_url: "http://192.168.33.10"
      browser_name: chrome
      goutte: ~
      selenium2: ~
```

and my .feature file looks like this:

```
Feature: Admin activates plugin
  In order to use the plugin
  As a WordPress user
  I should be able to activate it

  Scenario: Enable the dolly plugin
    Given there are plugins
      | plugin    | status  |
      | hello.php | enabled |
    When I go to "/wp-admin/"
    Then I should see a "#dolly" element
```

 I get error when try to run Behat:

`PHP Fatal error:  Call to undefined function StephenHarris\WordPressBehatExtension\Context\Plugins\activate_plugin() in /home/vagrant/my-plugin/vendor/stephenharris/wordpress-behat-extension/src/Context/Plugins/WordPressPluginContext.php on line 21
`

What did I do wrong? I use vccw vagrant and run tests after I ssh into it.
